In [1]:
import numpy as np
a = np.zeros(5)



In [2]:
a

array([0., 0., 0., 0., 0.])

In [3]:
a.dtype


dtype('float64')

In [4]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [5]:
l = [1, 2, 3, 4, 5]
c = np.array(l)
c

array([1, 2, 3, 4, 5])

In [6]:
c.shape


(5,)

In [7]:
d = np.empty([4,4])
d

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061346e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [8]:
e = np.arange(1, 20, 4)
e

array([ 1,  5,  9, 13, 17])

In [10]:
e.size

5

In [12]:
e.shape


(5,)

In [14]:
x = [4, 9, 16, 25]
y = np.sqrt(x)
y

array([2., 3., 4., 5.])

In [15]:
z = np.power(x, 2)
z

array([ 16,  81, 256, 625], dtype=int32)

In [16]:
np.eye((5))


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
a = np.diag([2, 4, 8])
a 

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [18]:
result = np.array([15, 20, 24, 28, 32, 40, 48, 50])
np.where(result>25, "PASS", "FAIL")


array(['FAIL', 'FAIL', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS'],
      dtype='<U4')

In [19]:
a = np.linspace(1, 5, 5)
a

array([1., 2., 3., 4., 5.])

In [20]:
x = np.sin(np.pi/2)
x

1.0

In [21]:
y = np.cos(np.pi/2)
y

6.123233995736766e-17

In [23]:
x = np.lcm(15, 30)
x

30

In [24]:
y = np.gcd(30, 6)
y 

6

In [27]:
z = np.prod([x, y])
z

180

In [28]:
x = np.array([1, 2, 2, 3, 4, 5, 6, 6, 7])
y = np.unique(x)
y

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
z = x.max()
z

7

In [30]:
x.min()

1

In [32]:
a = np.array([[2, 4],[6, 3]])
np.sort(a)

array([[2, 4],
       [3, 6]])

In [34]:
x2 = np.arange(4, 12)
x2

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x = np.dot(a, b)
x

32

In [36]:
x = np.arange(12).reshape(3,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
x.sum(axis = 0)


array([12, 15, 18, 21])

In [39]:
x.sum(axis = 1)


array([ 6, 22, 38])

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
a.mean()

3.5

In [41]:
a.sum()

21

In [42]:
a.cumsum()


array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [43]:
a.prod()

720

In [44]:
a.cumprod()

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [45]:
a>3

array([False, False, False,  True,  True,  True])

In [46]:
a<4

array([ True,  True,  True, False, False, False])

In [49]:
x = np.random.randn(2, 3)
y = np.random.randn(3, 2)

In [51]:
a = x.dot(y)
a

array([[-1.45511524,  2.16433791],
       [ 1.22545439,  0.23728253]])

In [52]:
a.transpose()


array([[-1.45511524,  1.22545439],
       [ 2.16433791,  0.23728253]])

In [54]:
x = np.array([[2,1,1], [4, 2, 1], [2,1,1]]) 
y = np.linalg.det(x) 
y

0.0

In [55]:
x.trace()


5

In [56]:
x.any()


True

In [57]:
x.all()


True

In [59]:
a = np.array([[0, 2, 6, 0],
              [1, 0, 2, 0]])
b = np.count_nonzero(a)
b

4

In [60]:
c = np.count_nonzero(a, axis=0)
c

array([1, 1, 2, 0], dtype=int64)

In [61]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
b = a[[1, 0, 2], :]
b

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [64]:
c = a[:, : : -1]
c

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])